apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdengine.fullname" . }}
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Release.Name }}6030
      port: {{ .Values.service.ports.tcp6030 }}
      protocol: TCP
    - name: {{ .Release.Name }}6041
      port: {{ .Values.service.ports.tcp6041 }}
      protocol: TCP
  selector:
    {{- include "tdengine.selectorLabels" . | nindent 4 }}
